version: 1.2
workflows:
  - subclass: WDL
    name: AnnotateSTRs
    primaryDescriptorPath: /functional_annotation/AnnotateSTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /functional_annotation/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
