version: 1.2
workflows:
  - subclass: WDL
    name: AnnotateSTRs
    primaryDescriptorPath: /wdl/AnnotateSTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAnnotate
    primaryDescriptorPath: /wdl/AnnotateSVAnnotate.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /wdl/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAN
    primaryDescriptorPath: /wdl/AnnotateSVAN.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateExternalAFs
    primaryDescriptorPath: /wdl/AnnotateExternalAFs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSingletonReads
    primaryDescriptorPath: /wdl/AnnotateSingletonReads.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BenchmarkSNVAnnotations
    primaryDescriptorPath: /wdl/BenchmarkSNVAnnotations.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RunTRGT
    primaryDescriptorPath: /wdl/RunTRGT.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
