version: 1.2
workflows:
  - subclass: WDL
    name: AnnotateExternalAFs
    primaryDescriptorPath: /wdl/AnnotateExternalAFs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  
  - subclass: WDL
    name: AnnotateSTRs
    primaryDescriptorPath: /wdl/AnnotateSTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAnnotate
    primaryDescriptorPath: /wdl/AnnotateSVAnnotate.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /wdl/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
